"""
Oracle Utilities CC&B (Customer Care & Billing) schema models.

Models the core Oracle CC&B tables used in utility CIS systems. These dataclasses
mirror the actual CC&B table structures — field names, status flags, and relationships
are faithful to the Oracle schema so that integration mappings are straightforward.

Typical data flow:
    CC&B Extract  -->  CIS Adapter  -->  Schema Parser  -->  Payment Platform

Reference: Oracle Utilities CC&B 2.9.x Data Dictionary
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Optional


class AcctStatusFlg(str, Enum):
    """CI_ACCT.ACCT_STATUS_FLG — account lifecycle states."""
    ACTIVE = "20"
    SUSPENDED = "40"
    CLOSED = "60"
    WRITTEN_OFF = "80"


class BillStatusFlg(str, Enum):
    """CI_BILL.BILL_STATUS_FLG — bill completion states."""
    COMPLETE = "C"
    PENDING = "P"
    FROZEN = "F"
    CANCELLED = "X"
    ERROR = "E"


class SaStatusFlg(str, Enum):
    """CI_SA.SA_STATUS_FLG — service agreement lifecycle."""
    ACTIVE = "20"
    PENDING_START = "30"
    PENDING_STOP = "40"
    STOPPED = "60"
    CANCELLED = "70"


class PerOrBusFlg(str, Enum):
    """CI_PER.PER_OR_BUS_FLG — person vs. business entity."""
    PERSON = "P"
    BUSINESS = "B"


@dataclass
class CiAcct:
    """
    Oracle CC&B CI_ACCT — the master account record.

    Each row represents a billing account in the CIS. A single person (CI_PER)
    can own multiple accounts, and each account can have multiple service
    agreements (CI_SA) and bills (CI_BILL).
    """
    acct_id: str
    cis_division: str
    setup_dt: date
    acct_status_flg: AcctStatusFlg = AcctStatusFlg.ACTIVE
    currency_cd: str = "USD"
    coll_cl_cd: Optional[str] = None
    alert_info: Optional[str] = None
    bill_cycle_cd: Optional[str] = None
    bill_after_dt: Optional[date] = None
    mailing_prem_id: Optional[str] = None
    protect_acct_flg: str = "N"
    version: int = 1

    # Linked person — populated after join to CI_ACCT_PER
    per_id: Optional[str] = None

    def is_active(self) -> bool:
        return self.acct_status_flg == AcctStatusFlg.ACTIVE

    def is_eligible_for_payment(self) -> bool:
        """Account must be active or suspended (on payment plan) to accept payments."""
        return self.acct_status_flg in (AcctStatusFlg.ACTIVE, AcctStatusFlg.SUSPENDED)


@dataclass
class CiPer:
    """
    Oracle CC&B CI_PER — the person/business entity.

    Stores the customer identity. One person record can link to many accounts
    via CI_ACCT_PER (not modeled here for simplicity).
    """
    per_id: str
    per_or_bus_flg: PerOrBusFlg = PerOrBusFlg.PERSON
    emailid: Optional[str] = None
    lang_cd: str = "ENG"
    life_support_flg: str = "N"
    name1: Optional[str] = None
    ovrd_mail_name1: Optional[str] = None
    phone: Optional[str] = None
    version: int = 1

    @property
    def is_life_support(self) -> bool:
        """Life-support customers have disconnect protection and priority handling."""
        return self.life_support_flg == "Y"

    @property
    def is_business(self) -> bool:
        return self.per_or_bus_flg == PerOrBusFlg.BUSINESS


@dataclass
class CiBill:
    """
    Oracle CC&B CI_BILL — the bill header.

    Generated by the CC&B billing batch. Each bill aggregates one or more
    bill segments (CI_BILL_SEG), one per service agreement billed in that cycle.
    """
    bill_id: str
    acct_id: str
    bill_dt: date
    due_dt: date
    bill_amt: Decimal
    prev_unpaid_amt: Decimal = Decimal("0.00")
    tot_amt_due: Decimal = Decimal("0.00")
    bill_status_flg: BillStatusFlg = BillStatusFlg.COMPLETE
    cr_note_flg: str = "N"
    bill_cyc_cd: Optional[str] = None
    win_start_dt: Optional[date] = None
    version: int = 1

    # Populated after joining segments
    segments: list[CiBillSeg] = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.tot_amt_due == Decimal("0.00") and self.bill_amt:
            self.tot_amt_due = self.bill_amt + self.prev_unpaid_amt

    @property
    def is_credit_note(self) -> bool:
        return self.cr_note_flg == "Y"

    @property
    def is_past_due(self) -> bool:
        return date.today() > self.due_dt and self.tot_amt_due > Decimal("0.00")

    @property
    def is_payable(self) -> bool:
        return (
            self.bill_status_flg == BillStatusFlg.COMPLETE
            and self.tot_amt_due > Decimal("0.00")
        )


@dataclass
class CiBillSeg:
    """
    Oracle CC&B CI_BILL_SEG — individual bill segment.

    One segment per service agreement (SA) billed in a given bill. The segment
    carries the charges for a single service (electric, gas, water) for the
    billing period defined by START_DT / END_DT.
    """
    billseg_id: str
    bill_id: str
    sa_id: str
    start_dt: date
    end_dt: date
    calc_amt: Decimal = Decimal("0.00")
    sq_override_flg: str = "N"
    billseg_stat_flg: str = "50"  # 50 = frozen (normal state after billing)
    closing_billseg_flg: str = "N"
    version: int = 1


@dataclass
class CiSa:
    """
    Oracle CC&B CI_SA — service agreement.

    The SA links an account to a specific utility service at a given premise.
    It carries the rate schedule, service type, and lifecycle status.
    """
    sa_id: str
    acct_id: str
    sa_type_cd: str
    sa_status_flg: SaStatusFlg = SaStatusFlg.ACTIVE
    start_dt: Optional[date] = None
    end_dt: Optional[date] = None
    char_prem_id: Optional[str] = None
    cis_division: Optional[str] = None
    sa_rel_type_cd: Optional[str] = None
    version: int = 1

    def is_active(self) -> bool:
        return self.sa_status_flg == SaStatusFlg.ACTIVE

    @property
    def service_category(self) -> str:
        """Derive the broad service category from the SA type code prefix."""
        prefix = self.sa_type_cd.split("-")[0] if "-" in self.sa_type_cd else ""
        return {
            "E": "electric",
            "G": "gas",
            "W": "water",
            "S": "sewer",
        }.get(prefix, "unknown")
